# Generated by Django 5.1.4 on 2026-04-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_event_lieu_news_date_news_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='formati',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
